from django.urls import path
from AppProductos import views
urlpatterns = [
    path("", views.inicio, name="Inicio"),
    path('productos/', views.productos, name="productos"),
    path('cliente/', views.cliente, name="cliente"),
    path('stock/', views.stock, name="stock"),
    path("busquedaproducto/", views.buscarproducto, name= 'busqueda_producto'),
    path("busquedacliente/", views.buscarcliente, name= 'busqueda_cliente'),
    path("busquedastock/", views.buscarstock, name= 'busqueda_stock'),
    path("buscar/", views.buscar),
    path("buscarc/", views.buscarc),
    path("buscars/", views.buscars),
    path("leerproducto/", views.leer_producto),
    path("leercliente/", views.leer_cliente),
    path("leerstock/", views.leer_stock),
    path("crearProducto/", views.crear_producto),
    path("crearCliente/", views.crear_cliente),
    path("crearStock/", views.crear_stock),
    path("editarProducto/", views.editar_producto),
    path("editarCliente/", views.editar_cliente),
    path("editarStock/", views.editar_Stock),
    path("eliminarProducto/", views.eliminar_producto),
    path("eliminarCliente/", views.eliminar_cliente),
    path("eliminarStock/", views.eliminar_stock),
    path("productos/list/", views.ProductosList.as_view(), name='List_producto'),
    path("cliente/list/", views.ClienteList.as_view(), name='List_cliente'),
    path("stock/list/", views.StockList.as_view(), name='List_stock'),
    path("producto/create/", views.ProductosCreate.as_view(), name='New'),
    path("cliente/create/", views.Clientecreate.as_view(), name='New'),
    path("stock/create/", views.Stockcreate.as_view(), name='New'),
    path("producto/edit/<pk>", views.ProductoEdit.as_view(), name='Edit_producto'),
    path("cliente/edit/<pk>", views.ClienteEdit.as_view(), name='Edit_cliente'),
    path("stock/edit/<pk>", views.StockEdit.as_view(), name='Edit_stock'),
    path("producto/detail/<pk>", views.ProductoDetail.as_view(),
         name='Detail_producto'),
    path("cliente/detail/<pk>", views.ClienteDetail.as_view(), name='Detail_cliente'),
    path("stock/detail/<pk>", views.StockDetail.as_view(), name='Detail_stock'),
    path("producto/delete/<pk>", views.ProductoDelete.as_view(),
         name='Delete_producto'),
    path("cliente/delete/<pk>", views.ClienteDelete.as_view(), name='Delete_cliente'),
    path("stock/delete/<pk>", views.StockDelete.as_view(), name='Delete_stock'),


]
