# Generated by Django 4.1.3 on 2022-12-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProductos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(max_length=40),
        ),
    ]
